### ISSUE TITLE
"Login to your New Relic account" should deep link to the correct browser app

### ISSUE THREAD

**Issue by coopr** [rtCamp/rt-newrelic-browser#19]
When I click this link, I get sent to the default New Relic login page https://rpm.newrelic.com/login

I should instead get deep-linked to the Browser app overview page related to my WordPress site https://rpm.newrelic.com/accounts/ACCOUNT_ID/browser/BROWSER_APP_ID

![new_relic_options_ _iona_dreaming_ _wordpress](https://cloud.githubusercontent.com/assets/94904/5782985/166b47b2-9d74-11e4-9db6-286b6a7e519b.jpg)

**Comment by ItsMePN** [comment]
@coopr  - In case if user already has New Relic account and then he starts using our plugin by just entering the API key, then we don't get the account ID. Hence in that case 'Login to your New Relic Account' is not deep-linked. Otherwise we have deep-linked it when user creates the New Relic account using plugin.

**Comment by coopr** [comment]
Hey, good point! I forgot that the account ID was unavailable from our API. I'm asking around for work-around, but it seems unlikely, so I suggest you close this issue ; ) Thanks!
